config/routes.rb
Art::Application.routes.draw do
  get "users/new"

  root 'home#index'
  match '/join', 	to: 'users#new',	via: 'get'
  match '/signout',	to: 'sessions#destroy',	via: 'delete'

  resources :users
  resources :sessions, only: [:create, :destroy]

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { 
		# stadardize storage in database
		self.email = email.downcase 
		self.name  = name.downcase
	}
	

	# Name is two or three words without numbers or 
	# symbols (except hyphen)
	VALID_NAME_REGEX = /\A[a-z-]+[ ][a-z-]+([ ][a-z-]+)?([ ][IVXL]+)?\z/i
	validates :name, length: { maximum: 64 }, format: { with: VALID_NAME_REGEX }, uniqueness: { case_sensitive: false }

	# Email validation
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 64 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	# Password validation
	validates :password, length: { maximum: 64, minimum: 6 }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(name: params[:session][:name].downcase)
		if user.nil?
			user = User.find_by(email: params[:session][:name].downcase)
		end

		if user && user.authenticate(params[:session][:password])
			sign_in(user)
			#	session[:remember_token] = user.id
			if :from_home?
				redirect_to user
			else 
				redirect_to :back
			end
		else
			flash[:error] = "Not a valid email/password synthesis."
			redirect_to :back	
		end

			
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	  @user = User.new
  end
 
  def show
	  @user = User.find(params[:id])
  end

  def create
	@user = User.new(user_params)
	if @user.save
		flash[:new_profile] = "Enjoy your new account!"
		sign_in(@user)
		# session[:remember_token] = user.id
		redirect_to @user
	else
		render 'new'
	end
  end

  private 
  	def user_params 
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:remember_token] = user.id
		# TODO: Add sign in across browser sessions
	end

	def sign_out
		session[:remember_token] = nil
	end

	def current_user
		User.find_by_id(session[:remember_token])
	end

	def signed_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
	  #if user.show_gravatar
		grav_id = Digest::MD5::hexdigest(user.email.downcase)
		grav_url = "https://secure.gravatar.com/avatar/#{grav_id}"
		image_tag(grav_url, alt: user.name, class: "gravatar")	   
	  #end
	end
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<div class="fgbox">
	Introductory Content. Here is <a href='#'>a link</a> to test.
</div>
<div class="fgbox">

<h2>Model</h2>
<div class="essay">
Artists will be able to publish essays and comment on their own and other essays. A comment 

may either be a root comment or a reply. A root comment is attached to a specific part of an 

essay, a reply to another comment.

Artists may also highlight comments they find particularly insightful and record quotes from 

essays. They can bookmark essays they wish to read later.

The following is a rough schema for a relational database.

<h3>Artist</h3>

name

password

email

<h3>Essay</h3>

artist_id

content

post_time

post_anon? (give user to option to post some essays without their name)

<h3>Comment</h3>

essay_id

artist_id

content

post_time

<h3>Root_comment</h3>

comment_id

position (position in the essay, can be done by line number range)

<h3>Reply</h3>

comment_id

parent_id

<h3>Quote</h3>

essay_id

artist_id

content (perhaps just specified by position in essay if we want to save space)

position (so we can jump back to place in essay immediately)

<h3>Highlight</h3>

aritst_id

comment_id

<h3>Bookmark</h3>

essay_id

user_id

mark_time

We would also want heuristics to suggest essays and figure out which comments to display if 

there’s a densely discussed portion of the essay.
</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
<h1>The Artist's War</h1>
<div id="navbar">
	<ul class="nav">
		<% if signed_in? %>
			<li><%= link_to 'Home', current_user %></li>
		<% else %>
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'Register', join_path %></li>
		<% end %>
	</ul>

	<div class="signin">
	<% if signed_in? %> 
		<%= link_to "Sign out", signout_path, method: :delete %>
	<% else %>
			<%= form_for(:session, url: sessions_path) do |f| %>
				<%= f.text_field :name %>
				<%= f.password_field :password %>
				<%= hidden_field_tag :from_home?, current_page?(root_url) %>
				<%= f.submit "Sign in", class: "button" %>
			<% end %>
	<% end  %>
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | The Artist's War</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Belleza|Quattrocento|Julius+Sans+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>
	<div id="container">
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>"><%= value %></div>
	<% end %>	
		<%= yield %>
	</div>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="errors">
	You erred.
	<ul>
	<% @user.errors.full_messages.each do |e| %>
		<li><%= e %>.</li>
	<% end %>
	</ul>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Join") %> 
<%= render 'shared/error_messages' %>
<div id="registration" class="fgbox">
	<%= form_for(@user) do |f| %>
	 <%= f.label :name, "Pen Name" %>
	 <%= f.text_field :name %>

	 <%= f.label :email %>
	 <%= f.text_field :email %>

	 <%= f.label :password %>
	 <%= f.password_field :password %>

	 <%= f.label :password_confirmation, "Again" %>
	 <%= f.password_field :password_confirmation %>
	<div class="center">
	 <%= f.submit "Register", class: "button" %>
	</div>
	<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> 
<div class="fgbox">
	<%#= gravatar_for @user %>
	<%= @user.name %><br/>
	<%= @user.email %>
</div>